#.travis.yml

language: node_js
node_js:
  - "10.14"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - npm run test:unit
  - npm run build
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy; fi

notifications:
  email:
    on_failure: change